gcloud run deploy後にtrafficを変える

diff --git a/.github/workflows/deploy_to_production.yml b/.github/workflows/deploy_to_production.yml
--- a/.github/workflows/deploy_to_production.yml
+++ b/.github/workflows/deploy_to_production.yml
@@ -74,3 +74,42 @@ jobs:
             --set-env-vars="TWITCH_OAUTH2_CLIENT_ID=${TWITCH_OAUTH2_CLIENT_ID}" \
             --set-env-vars="TWITCH_OAUTH2_SECRET=${TWITCH_OAUTH2_SECRET}" \
             --allow-unauthenticated
+
+  publish:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Add SHORT_SHA env property with commit short sha
+        run: echo "SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)" >> "$GITHUB_ENV"
+      - id: "auth"
+        uses: "google-github-actions/auth@v0"
+        with:
+          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
+      - name: Update traffic
+        run: |
+          retry_count=0
+          max_retries=5
+
+          while [ $retry_count -lt $max_retries ]; do
+            gcloud beta run services update-traffic "$SERVICE_NAME" \
+              --project="$PROJECT_ID" \
+              --platform=managed \
+              --to-tags="master-${SHORT_SHA}=100" \
+              --region="asia-northeast1"
+
+            exit_status=$?
+
+            if [ $exit_status -eq 0 ]; then
+              echo "Command succeeded!"
+              break
+            else
+              echo "Command failed. Retrying in 10 seconds... ($((retry_count+1))/$max_retries)"
+              retry_count=$((retry_count+1))
+              sleep 10
+            fi
+          done
+
+          if [ $retry_count -eq $max_retries ]; then
+            echo "Command failed after $max_retries attempts. Exiting."
+            exit 1
+          fi
